# Default values for the User Service Helm chart

replicaCount: 1
image:
  repository: ghcr.io/nooshet-backend/user-service
  tag: development-c559d35
  pullPolicy: IfNotPresent
  imagePullSecrets:
    - name: ghcr-secret
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: user.nooshet.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources:
  limits:
    memory: 512Mi
    cpu: 500m
  requests:
    cpu: 250m
    memory: 256Mi
autossl: {}
istio:
  enabled: true
apiGatewayFullname: "api-gateway"
database:
  host: postgresql-user
  port: 5432
  name: nooshet_user
  user: nooshet_user
  password: user_password_123
redis:
  host: "redis"
  port: "6379"
env:
  JWT_SECRET: "change-me-in-prod-please-use-a-longer-secret-key-123456"
  JWT_ISSUER: "nooshet"
  SPRING_PROFILES_ACTIVE: "dev"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_TIMEOUT: "2000ms"
  IDENTITY_SERVICE_URL: "http://identity-service:8080"
  JAVA_OPTS: "-XX:TieredStopAtLevel=1 -Xss256k -Xmx448m"
