# Default values for the User Service Helm chart

replicaCount: 1
image:
  repository: ghcr.io/nooshet-backend/user-service
  tag: development-4b14ae1
  pullPolicy: IfNotPresent
  imagePullSecrets:
    - name: ghcr-secret
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: user.nooshet.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources: {}
autossl: {}
istio:
  enabled: true
apiGatewayFullname: "api-gateway"
database:
  host: postgresql-user
  port: 5432
  name: nooshet_user
  user: nooshet_user
  password: user_password_123
redis:
  host: redis
  port: 6379
