apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "user-service.fullname" . }}-authz
spec:
  selector:
    matchLabels:
      {{- include "user-service.selectorLabels" . | nindent 6 }}
  action: ALLOW
  rules:
    - from:
        - source:
            {{- if and .Values.istio (hasKey .Values.istio "authorization") (hasKey .Values.istio.authorization "internalCallers") }}
            principals:
              {{- toYaml .Values.istio.authorization.internalCallers | nindent 14 }}
            {{- else }}
            principals: []
            {{- end }}
