apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ include "user-service.fullname" . }}-peer-auth
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "user-service.selectorLabels" . | nindent 6 }}
  mtls:
    mode: STRICT
